
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.prod
    env_file:
      - .env.prod
    restart: always
    expose:
      - 8000
    volumes:
      - ./backend/app:/app
      - static_volume:/app/static

  nginx:
    build: nginx
    env_file: .env.prod
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - static_volume:/app/static
      - certs:/etc/letsencrypt
    depends_on:
      - backend

volumes:
  static_volume:
  certs:
