
services:
  backend:
    build:
      context: backend
    env_file:
      - .env.dev
    restart: unless-stopped
    volumes:
      - ./backend/app:/app
      - static_volume:/app/static
    ports:
      - '8000:8000'

  health-checker:
    build:
      context: ./checker
    container_name: checker
    restart: unless-stopped
    volumes:
      - ./checker:/checker
    env_file:
      - ./checker/.env
    depends_on:
      - backend

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

volumes:
  static_volume:
