
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.prod
    env_file:
      - .env.prod
    restart: always
    expose:
      - 8000
    volumes:
      - ./backend/app:/app
      - static_volume:/app/static

  health-checker:
    build:
      context: ./checker
    container_name: checker
    restart: always
    volumes:
      - ./checker:/app
    env_file:
      - ./checker/.env
    depends_on:
      - backend

  nginx:
    build: nginx
    env_file: .env.prod
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - static_volume:/app/static
      - certs:/etc/letsencrypt
    depends_on:
      - backend

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "8883:8883"              # TLS порт
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - certs:/etc/letsencrypt:ro

volumes:
  static_volume:
  certs:
