
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.prod
    env_file:
      - .env.prod
    restart: always
    expose:
      - 8000
    volumes:
      - ./backend/app:/app
      - static_volume:/app/static

  nginx:
    build: nginx
    env_file: .env.prod
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - static_volume:/app/static
      - certs:/etc/letsencrypt
    depends_on:
      - backend

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

volumes:
  static_volume:
  certs:
